apiVersion: apps/v1
kind: Deployment
metadata:
  name: ic-webapp-prod
  namespace: icgroup
  labels:
    app: ic-webapp
    env: prod
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: ic-webapp-pods
  template:
    metadata:
      name: ic-webapp-template
      labels:
        app: ic-webapp-pods
    spec:
      containers:
      - image: younesabdh/ic-webapp:v1.0
        name: ic-webapp-ctnr
        env:
        - name: ODOO_URL
          value: http://192.168.99.10:30200
        - name: PGADMIN_URL
          value: http://192.168.99.10:30300
        ports:
        - containerPort: 8080
