apiVersion: v1
kind: Service
metadata:
  name: ic-webapp-nodeport
  namespace: icgroup
  labels:
    app: ic-webapp
    env: prod
spec:
  type: NodePort
  selector:
    app: ic-webapp-pods
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080