apiVersion: apps/v1
kind: Deployment
metadata:
  name: ic-webapp
  namespace: "ic-group"
  labels:
    env: prod
    app: ic-webapp
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: ic-webapp
  template:
    metadata:
      labels:
        app: ic-webapp
    spec:
      containers:
      - name: ic-webapp-ctr
        image: younesabdh/ic-webapp:v1.0
        env:
        - name: ODOO_URL
          value: http://http://192.168.56.10:30069/
        - name: PGADMIN_URL
          value: http://192.168.56.10:30100/
        ports:
        - containerPort: 8080