apiVersion: v1
kind: Service
metadata:
  name: ic-webapp-nodeport
  namespace: icgroup
spec:
  type: NodePort
  ports:
  - targetPort: 8080
    port: 8080
    nodePort: 30080
  selector:
    app: ic-webapp-pods