version: "3.8"

services:
  ic-webapp:
    container_name: ic-webapp-ctr
    image: younesabdh/ic-webapp:1.0
    environment:
          - ODOO_URL=http://192.168.99.11:8069
          - PGADMIN_URL=http://192.168.99.11:5050
    networks:
      - ic_webapp_network
    ports:
      - 8000:8000

  odoo:
    image: odoo:13.0
    container_name: odoo-ctnr
    depends_on:
      - postgres
    environment:
      - USER=odoo_user
      - PASSWORD=odoo_password
      - HOST=postgres
    networks:
      - ic_webapp_network
    ports:
      - 8069:8069
    volumes:
      - odoo-web-data:/var/lib/odoo
      - /data_docker/config:/etc/odoo
      - /data_docker/addons:/mnt/extra-addons

  postgres:
    image: postgres:10
    container_name: postgres-ctnr
    restart: unless-stopped
    environment:
      - POSTGRES_USER=odoo_user
      - POSTGRES_PASSWORD=odoo_password
      - POSTGRES_DB=postgres
    networks:
      - ic_webapp_network
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-ctnr
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin_password
    networks:
      - ic_webapp_network
    ports:
      - 5050:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ${PWD}/servers.json:/pgadmin4/servers.json

networks:
  ic_webapp_network:
    driver: bridge

volumes:
  odoo-web-data:
  pgadmin-data:
  pgdata: