version: '3.8'
services:
  pgadmin:
    container_name: pgadmin-ctnr
    image: dpage/pgadmin4
    networks:
      - ic_pgadmin_network
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com'
      - 'PGADMIN_DEFAULT_PASSWORD=pgadmin_password'
    ports:
      - "5050:80"
    volumes:
      - '${PWD}/servers.json:/pgadmin4/servers.json'
      - 'pgadmin_data:/var/lib/pgadmin'

volumes:
  pgadmin_data:

networks:
  ic_pgadmin_network:
    driver: bridge
    name: ic_pgadmin_network
