---
- name: "Generate the Docker Compose file"
  template:
    src: "icwebapp-docker-compose.yml.j2"  # Path to the Jinja2 template
    dest: "/home/{{ ansible_user }}/icwebapp-docker-compose.yml"  # Destination path
    mode: "0644"  # Permissions for the file

- name: "Deploy Odoo using Docker Compose"
  command: "docker-compose -f /home/{{ ansible_user }}/icwebapp-docker-compose.yml up -d"