apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: "ic-group"
  labels:
    env: prod
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgres
