---
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: postgres-scrt
  namespace: icgroup
  labels:
    env: prod
    app: postgres
type: Opaque
data:
  POSTGRES_PASSWORD: b2Rvbw==