apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-prod
  namespace: icgroup
  labels:
    app: pgadmin
    env: prod
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pgadmin-pods
  template:
    metadata:
      labels:
        app: pgadmin-pods
    spec:
      containers:
      - image: dpage/pgadmin4
        name: pgadmin-ctnr
        securityContext:
         runAsUser: 0
         runAsGroup: 0
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: admin@pgadmin.com
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgadmin-secret
              key: PGADMIN_DEFAULT_PASSWORD
        volumeMounts:
          - name: servers
            mountPath: /pgadmin4/servers.json
          - name: pg-volume
            mountPath: /var/lib/pgadmin
      volumes:
        - name: servers
          configMap:
            name: pgadmin-configmap
#          items:
#          - key: servers.json
#            path: servers.json
        - name: pg-volume
          hostPath:
            path: /pg-data
            type: DirectoryOrCreate