apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: pgadmin-secret
  namespace: icgroup
  labels:
    env: prod
    app: pgadmin
type: Opaque
data:
  PGADMIN_DEFAULT_PASSWORD: cGFzc3dvcmQ=