apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-pv
  namespace: "ic-group"
  labels:
    type: local
    env: prod
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data_k8s/pgadmin4"