apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: pgadmin-secret
  namespace: "ic-group"
  labels:
    env: prod
    app: pgadmin
type: Opaque
data:
  pgadmin-default-password: bXlwd2Q=