apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  labels:
    app: pgadmin
    env: prod
  namespace: "ic-group"
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - image: dpage/pgadmin4
        name: pgadmin-ctr
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: admin@pgadmin.com
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgadmin-secret
              key: PGADMIN_DEFAULT_PASSWORD
        ports:
        - containerPort: 5050
        volumeMounts:
        - name: pgadmin-config
          mountPath: /pgadmin4/servers.json
          subPath: servers.json
        - name: pgadmin-data
          mountPath: /var/lib/pgadmin
      volumes:
      - name: pgadmin-config
        configMap:
          name: pgadmin-configmap
          items:
          - key: servers.json
            path: servers.json    
      - name: pgadmin-data
        persistentVolumeClaim:
          claimName: pgadmin-pvc