apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  labels:
    app: odoo
    env: prod
  namespace: "ic-group"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
      - name: odoo
        image: odoo:16
        env:
        - name: HOST
          value: postgres-svc
        - name: USER
          value: odoo
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: odoo
              key: PASSWORD 
        ports:
        - containerPort: 8069
          name: odoo
        volumeMounts:
        - name: odoo-inside-storage
          mountPath: /etc/odoo
        - name: odoo-lib-storage
          mountPath: /var/lib/odoo
        - name: odoo-addons-storage
          mountPath: /mnt/extra-addons
      volumes:
      - name: odoo-inside-storage
        hostPath:
          path: /data/odoo/config
      - name: odoo-lib-storage
        persistentVolumeClaim:
          claimName: odoo-pvc
      - name: odoo-addons-storage
        hostPath:
          path: /data/odoo/addons